### ISSUE TITLE
Registered names has single-character state

### ISSUE THREAD

**Issue by waldoj** [openva/vabusinesses.org#11]
`8_registered_names.json` and `8_registered_names.csv` only includes the first character of the state name. But I can't see why—the table map for that column looks like this:

``` yaml
- name:        res-state
  alt_name:    state
  description: State of Requestor
  group:       address
  type:        A
  start:       332
  length:      2
  search: 
    match:     exact
```

Figure out why the second character is getting lopped off and fix it.
